'use server';

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { logAction } from "@/modules/audit/logger";

export async function customerApproveQuote(quoteId: string) {
    try {
        const quote = await prisma.fenceQuote.findUnique({
            where: { id: quoteId },
            include: { customer: true }
        });

        if (!quote) throw new Error("Quote not found");
        if (quote.status !== 'SENT') throw new Error("Only sent quotes can be approved by customer");

        // 1. Generate Invoice Number
        const count = await prisma.invoice.count();
        const invoiceNumber = `INV-${new Date().getFullYear()}-${(count + 1).toString().padStart(4, '0')}`;

        // 2. Transaction: Approve Quote + Create Invoice
        const [updatedQuote, invoice] = await prisma.$transaction([
            prisma.fenceQuote.update({
                where: { id: quoteId },
                data: { status: 'APPROVED' }
            }),
            prisma.invoice.create({
                data: {
                    quoteId: quote.id,
                    customerId: quote.customerId,
                    invoiceNumber,
                    subtotal: quote.subtotal,
                    vat: quote.vat,
                    total: quote.total,
                    status: 'PENDING',
                }
            })
        ]);

        // 3. Create the Job
        await prisma.job.create({
            data: {
                invoiceId: invoice.id,
                status: 'UNSCHEDULED',
                notes: 'Created via Customer Portal approval.'
            }
        });

        // 4. Log the activity
        await logAction({
            action: 'CUSTOMER_PORTAL_APPROVAL_AND_JOB_CREATED',
            entityType: 'FenceQuote',
            entityId: quoteId,
            performedBy: `Customer: ${quote.customer.name}`,
            metadata: { autoGeneratedInvoice: invoiceNumber }
        });

        revalidatePath(`/portal/${quote.customerId}`);
        return { success: true };
    } catch (err: any) {
        console.error("Portal Approval Error:", err);
        return { success: false, error: err.message };
    }
}
